[tool.poetry]
name = "xxmodelnqs"
version = "0.1.0"
description = ""
authors = ["SemyonSinchenko <semyonsinchenko@yahoo.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
numpy = ">=1.20.1"
matplotlib = ">=3.3.4"
cmake = ">=3.18.4"
mpi4py = ">=3.0.3"
netket = { git = "https://github.com/netket/netket.git", branch = "master" }
pandas = ">=1.2.3"
jupyterlab = ">=3.0.14"
jax = ">=0.2.21,<0.2.26"
jaxlib = ">=0.1.69"
proplot = "^0.9.7"

[tool.poetry.dev-dependencies]
pylint = "^2.12.1"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
